spring:
  application:
    name: patient
server:
  port: 8082
    
appointment:
  service:
    createAppointment:
      url: http://localhost:8083/createAppointment
    updateAppointment:
      url: http://localhost:8083/updateAppointment
    cancelAppointment:
      url: http://localhost:8083/cancelAppointment

user:
  service:
    url: http://localhost:8093/signUpUser

logging:
  level:
    org.springframework.security: DEBUG
    
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: medilink
      clientSecret: Password
      accessTokenUri: http://localhost:8093/oauth/token
      userAuthorizationUri: http://localhost:8093/oauth/authorize
    resource:
      userInfoUri: http://localhost:8093/user
      tokenInfoUri: http://localhost:8093/oauth/check_token
      filter-order: 3
              