spring: 
  application:
    name: zuulag  
    
server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
      
zuul:
  routes:
    practice: /practice/**
    patient: /patient/**
    appointment: /appointment/**
    authentication-service: /auth/**

    
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: medilink
      clientSecret: Password
      accessTokenUri: http://localhost:8093/oauth/token
      userAuthorizationUri: http://localhost:8093/oauth/authorize
    resource:
      userInfoUri: http://localhost:8093/user
      tokenInfoUri: http://localhost:8093/oauth/check_token
      filter-order: 3
  