spring:
  data:
    mongodb: 
      database: wellme
      host: localhost
      port: 27017
      
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/medilink
    username: root
    password: password      
    
appointment: 
  search:
    ByPracticeAndConsultants: select * from medilink.APPOINTMENT a where (a.practice_id || '-' || a.consultant_id) in (:practiceConsultantIds) 
  create:
    sql: insert into medilink.APPOINTMENT (appointment_id, patient_id, practice_id, consultant_id, appointment_date, start_time, end_time, ins_ts, upd_ts, ins_login, upd_login, status, special_instructions)
          values (:id, :patientId, :practiceId,:docId, :appointmentDate, :startTime, :endTime, :insTs, :updTs, :insLogin, :updLogin, :status, :specialInstructions)   
    