swagger: "2.0"
info:
  description: "API DEFINITIONS for medical appointment application"
  version: 1.0.0
  title: Medilink api YAML
  contact:
    email: "punit2512@gmail.com"
basePath: /search
schemes:
  - http
  - https
paths:
  /submitReview:
    post:
      produces:
        - application/json
      description: this API is to be used to submit review ratings and comments for consultants    
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: "#/definitions/SubmitConsultantReviewRequest"
      responses:
        '200':
          description: 200 status means review request is successful
        default:
          $ref: "#/definitions/Error"   

  /searchConsultants:
    post:
      produces:
        - application/json
      description: this API is to be used to search for available providers based on the search request parameters    
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: "#/definitions/SearchConsultantsRequest"
      responses:
        '200':
          description: List of search results with providers and their details
          schema:
            $ref: "#/definitions/SearchProvidersResponse"
        default:
          $ref: "#/definitions/Error"    
definitions:
  Error:
    type: object
    properties:
      errorMessage:
        type: string
        description: The error placeholder
  SearchProvidersResponse:
    description: response object for search providers api
    properties:
      results:
        type: array
        items:
          $ref: "#/definitions/SearchConsultantResultDto"
  SearchConsultantsRequest:
    description: request object to search for the consultants
    properties:
      practiceName: 
        type: string
      consultantName:
        type: string
      city:
        type: string
      area:
        type: string
      withinMiles:
        type: integer
      speciality:
        type: string
      zip:
        type: string
      insuranceProvider:
        type: string
      insuranceType:
        type: string
      coordinates:
        $ref: "#/definitions/Coordinates"                
  Address:
    properties:
      addressLine1:
        type: string   
      addressLine2:
        type: string
      area:
        type: string     
      city:
        type: string
      state:
        type: string
      stateCode:
        type: string
      zip:
        type: string
      country:
        type: string
      coordinates:
        $ref: "#/definitions/Coordinates" 
      isPrimary:
        type: boolean   
  Coordinates:
    properties:
      lattitude: 
        type: number
        format: double
      longitude: 
        type: number
        format: double
  Phone:
    required:
      - phoneNumber
    properties:
      phoneNumber:
        type: string
      phoneType:
        type: string
        description: Phone type e.g. office, mobile, home etc
        enum:
          - Office
          - Home
          - mobile
          - Other
      areaCode:
        type: string
      countryCode:
        type: string
      completePhoneNumber:
        type: string
  SocialProfile:
    description: social profile for the user, e.g. twitter, linked in, facebook, google user id etc details
    required:
      - socialType
      - socialId
    properties:
      socialType:
        type: string
      socialId:
        type: string
      socialDescription: 
        type: string
  AvailableSlotsDto:
    description: gives details of available AvailableSlotsDto
    required:
      - appointmentDate
    properties:
      appointmentStart:
        description: start date time of the appointment
        type: string
        format: date-time
      appointmentEnd:
        description: end date time of the appointment
        type: string
        format: date-time
  InsuranceProviderDto:
    description: details of insurance providers
    required:
      - insuranceProviderId
    properties:
      insuranceProviderId:
        type: integer
      insuranceProviderName:
        type: string
      insuranceTypes:
        type: array
        items:
          type: string
  SearchPracticeResultDto:
    description: practice search result details to be returned if practices are searched or for specific provider
    properties:
      practiceName:
        type: string
      practiceAddress:
        $ref: "#/definitions/Address"
      phones:
        type: array
        items:
          $ref: "#/definitions/Phone"
      practiceSocialProfiles:
        type: array
        items:
          $ref: "#/definitions/SocialProfile"
  SubmitConsultantReviewRequest:
    description: request for submitting the reviews for a provdier(consultant)
    properties:
      consultantId: 
        type: integer
        format: int64
      reviewedByName:
        type: string
      reviewedBy:
        type: integer
        format: int64
      reviewRating:
        type: int
      reviewedOn:
        type: string
        format: date-time
      reviewComments:
        type: string  
  ConsultantSignupDto:
    description: consultant information at the time of sign up
    properties:
        userName:
          type: string
        password:
          type: string  
        firstName: 
          type: string
        lastName: 
          type: string    
        middleName:
          type: string
        gender:
          type: string
        phoneNumber:
          type: string
        emails:
          type: array 
          items: 
            type: string 
        dateOfBirth: 
          type: string
          format: date-time
        NPI: 
          type: string
        profile:
          type: string
        profilePicUrl: 
          type: string  
        pictureURLs: 
          type: array 
          items: 
            type: string   
        addresses:
          type: array
          items:
            $ref: "#/definitions/Address"
        phones:
          type: array
          items:
            $ref: "#/definitions/Phone"   
        socialProfiles:
          type: array
          items:
            $ref: "#/definitions/SocialProfile"              
        userFullName:
          type: string
                                                               
  SearchConsultantResultDto:
    description: the provider details when searched for along with its other attributes e.g. slots, insurance plans, practices etc
    properties:
        consultantId:
          type: integer
          format: int64
        consultantName:
          type: string
        gender:
          type: string
        languages:
          type: array
          items:
            type: string    
        approvalPercentage:
          type: number
          format: double
        reviewsURL:
          type: string  
        addresses:
          type: array
          items:
            $ref: "#/definitions/Address"
        phones:
          type: array
          items:
            $ref: "#/definitions/Phone"   
        socialProfiles:
          type: array
          items:
            $ref: "#/definitions/SocialProfile"
        availableSlots:
          type: array
          items:
            $ref: "#/definitions/AvailableSlotsDto"
        specialities:
          type: array
          items:
            type: string
        insuranceProviderDto:
          type: array
          items:
            $ref: "#/definitions/InsuranceProviderDto"
        practices:
          type: array
          items:
            $ref: "#/definitions/SearchPracticeResultDto"  

  UpdateBoardCertificationRequest: 
    description: request body for adding board certifications
    properties:
      consultantId:
        type: integer
        format: int64
      cetifications:
        type: array
        items:
          $ref: "#/definitions/BoardCertificateDto"  
            
  BoardCertificate: 
    description: Board certificates of a consultant which can be added in separate steps
    properties:
      certificateId:
        type: integer
        format: int64
      certificate:
        type: string
      speciality:
        type: string
      subSpeciality:
        type: string
        
  UpdatePracticeAffiliationRequest: 
    description: request to update practice affiliations
    properties:
      properties:
      consultantId:
        type: integer
        format: int64
      practiceIds: 
        type: array
        items: 
          type: integer
          format: int64
  
  UpdateConsultantQualificationRequest:
    description: request for updating conusultant qualifications
    properties:
      consultantId: 
        type: integer
        format: int64
      qualifications:
        type: array
        items:
          $ref: "#/definitions/Qualification"      
          
  Qualification: 
    description: consultant qualification
    properties:
      qualification:
        type: string
      institute:  
          $ref: "#/definitions/Institute"  
      year:
        type: int
      field:
        type: string
                
  Institute:
    description: Educational institutes
    properties:
      instituteId:
        type: integer
        format: int64
      instituteName:
        type: string
      university:
        type: string
      address:
        type: string
      phone: 
        type: string                  
 
  UpdateLanguageSpokenRequest: 
    description: request to update language spoken by consultant
    properties:
      consultantId:
        type: string
      languages:
        type: array
        items:
          type: string
        
  UpdateInsuranceProviderRequest: 
    description: request to update insurance providers for consultant
    properties:
      consultantId:
        type: string
      insuranceProviderIds:
        type: array
        items:
          type: integer
          format: int64
  
  UpdateConsultantAwardDetails: 
    description: request to update award details of the consultant
    properties:
      consultantId:
        type: integer
        format: int64
      awards:
        type: array
        items:
          $ref: "#/definitions/AwardDetails"           

  AwardDetails: 
    description: the award details for a consultant
    properties:
      awardName:
        type: string
      awardDescription:
        type: string  
      issuingAuthority:
        type: string
      issuedOn:
        type: string
        format: date
  
  UpdateConsultantPapers: 
    description: request to update award details of the consultant
    properties:
      consultantId:
        type: integer
        format: int64
      awards:
        type: array
        items:
          $ref: "#/definitions/PublishedPaperDetails"    
        
  PublishedPaperDetails:      
    description: details of paper published by consultant
    properties:
      title: 
        type: string
      summary: 
        type: string  
      publishingAgency:
        type: string
      url:
        type: string  
      publishedOn:
        type: string
        format: date
                      
  GetAppointmentDetailsRequest: 
    description: request to get the appointment details for the consultant
    properties:
      consultantId:
        type: integer
        format: int64            
      startDate:
        type: string
        format: date
      statusesToInclude:
        type: array
        items:
          type: string
      daysToGoBack:
        type: integer

  UpdateAppointmentStatusRequest:
    description: request to update the appointment status to confirmed or decline as new requests come in.
    properties: 
      appointmentId: 
        type: integer
        format: int64                     
      updatedStatus: 
        type: string
      updateNotes: 
        type: string
  
  PracticeDto:
    description: practice object for creating and udpating practice
    properties:
      practiceId:
        type: integer
        format: int64      
      parentPracticeId: 
        type: integer
        format: int64                   
      practiceName: 
        type: string
      practiceDetails:    
        type: string
      specialitiesSupported:
        type: array
        items: 
          type: string
      addresses: 
        type: array
        items: 
          $ref: "#/definitions/Address"
      phones: 
        type: array
        items: 
          $ref: "#/definitions/Phone"
      insuranceProviderIds:
        type: array
        items:
          type: integer
          format: int64   
      consultantIds: 
         type: array
         items: 
           type: integer
           format: int64   
      socialProfiles: 
        type: array
        items: 
          $ref: "#/definitions/SocialProfile"            
      primaryAddresses:  
          $ref: "#/definitions/Address"   
                                             
  AdddEditPracticeRequest:
    description: Request to add/edit practices
    properties:
      practice:
        $ref: "#/definitions/PracticeDto"  
  

                             
 
                                                                     