swagger: "2.0"
info:
  description: "API DEFINITIONS for medical appointment application"
  version: 1.0.0
  title: Medilink api YAML
  contact:
    email: "punit2512@gmail.com"
basePath: /search
schemes:
  - http
  - https
paths:
  /searchConsultants:
    post:
      produces:
        - application/json
      description: this API is to be used to search for available providers based on the search request parameters    
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: "#/definitions/SearchConsultantsRequest"
      responses:
        '200':
          description: List of search results with providers and their details
          schema:
            $ref: "#/definitions/SearchProvidersResponse"
        default:
          $ref: "#/definitions/Error"    
definitions:
  Error:
    type: object
    properties:
      errorMessage:
        type: string
        description: The error placeholder
  SearchProvidersResponse:
    description: response object for search providers api
    properties:
      results:
        type: array
        items:
          $ref: "#/definitions/SearchConsultantResultDto"
  SearchConsultantsRequest:
    description: request object to search for the consultants
    properties:
      practiceName: 
        type: string
      consultantName:
        type: string
      city:
        type: string
      area:
        type: string
      withinMiles:
        type: integer
      speciality:
        type: string
      zip:
        type: string
      insuranceProvider:
        type: string
      insuranceType:
        type: string
      coordinates:
        $ref: "#/definitions/Coordinates"                
  Address:
    properties:
      addressLine1:
        type: string   
      addressLine2:
        type: string
      area:
        type: string     
      city:
        type: string
      state:
        type: string
      stateCode:
        type: string
      zip:
        type: string
      country:
        type: string
      coordinates:
        $ref: "#/definitions/Coordinates" 
      isPrimary:
        type: boolean   
  Coordinates:
    properties:
      lattitude: 
        type: number
        format: double
      longitude: 
        type: number
        format: double
  Phone:
    required:
      - phoneNumber
    properties:
      phoneNumber:
        type: string
      phoneType:
        type: string
        description: Phone type e.g. office, mobile, home etc
        enum:
          - Office
          - Home
          - mobile
          - Other
      areaCode:
        type: string
      countryCode:
        type: string
      completePhoneNumber:
        type: string
  SocialProfile:
    description: social profile for the user, e.g. twitter, linked in, facebook, google user id etc details
    required:
      - socialType
      - socialId
    properties:
      socialType:
        type: string
      socialId:
        type: string
      socialDescription: 
        type: string
  AvailableSlotsDto:
    description: gives details of available AvailableSlotsDto
    required:
      - appointmentDate
    properties:
      appointmentStart:
        description: start date time of the appointment
        type: string
        format: date-time
      appointmentEnd:
        description: end date time of the appointment
        type: string
        format: date-time
  InsuranceProviderDto:
    description: details of insurance providers
    required:
      - insuranceProviderId
    properties:
      insuranceProviderId:
        type: integer
      insuranceProviderName:
        type: string
      insuranceTypes:
        type: array
        items:
          type: string
  SearchPracticeResultDto:
    description: practice search result details to be returned if practices are searched or for specific provider
    properties:
      practiceName:
        type: string
      practiceAddress:
        $ref: "#/definitions/Address"
      phones:
        type: array
        items:
          $ref: "#/definitions/Phone"
      practiceSocialProfiles:
        type: array
        items:
          $ref: "#/definitions/SocialProfile"
  SearchConsultantResultDto:
    description: the provider details when searched for along with its other attributes e.g. slots, insurance plans, practices etc
    properties:
        consultantId:
          type: integer
          format: int64
        consultantName:
          type: string
        gender:
          type: string
        languages:
          type: array
          items:
            type: string    
        approvalPercentage:
          type: number
          format: double
        reviewsURL:
          type: string  
        addresses:
          type: array
          items:
            $ref: "#/definitions/Address"
        phones:
          type: array
          items:
            $ref: "#/definitions/Phone"   
        socialProfiles:
          type: array
          items:
            $ref: "#/definitions/SocialProfile"
        availableSlots:
          type: array
          items:
            $ref: "#/definitions/AvailableSlotsDto"
        specialities:
          type: array
          items:
            type: string
        insuranceProviderDto:
          type: array
          items:
            $ref: "#/definitions/InsuranceProviderDto"
        practices:
          type: array
          items:
            $ref: "#/definitions/SearchPracticeResultDto"
            